apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gameboard-ui.fullname" . }}
  labels:
    {{- include "gameboard-ui.labels" . | nindent 4 }}

data:
  settings.json: |
{{ .Values.settings | indent 4 }}
