{{- if .Values.giturl }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-cron"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  schedule: "*/{{ .Values.pollInterval | default 5 }} * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: "{{ .Release.Name }}"
          labels:
            app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
            app.kubernetes.io/instance: {{ .Release.Name | quote }}
            helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        spec:
          restartPolicy: Never
          initContainers:
          {{- include "mkdocs-material.git-container" . | nindent 12 }}
          containers:
          {{- include "mkdocs-material.mkdocs-container" . | nindent 12 }}
          volumes:
            {{- include "mkdocs-material.container-volumes" . | nindent 12 }}
{{- end }}
