{{- if .Values.giturl }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-cron"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  schedule: "*/{{ .Values.pollInterval | default 5 }} * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: "{{ .Release.Name }}"
          labels:
            app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
            app.kubernetes.io/instance: {{ .Release.Name | quote }}
            helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        spec:
          restartPolicy: Never
          initContainers:
          {{- include "mkdocs-material.git-container" . | nindent 12 }}
          containers:
          {{- include "mkdocs-material.mkdocs-container" . | nindent 12 }}
          volumes:
            - name: {{ include "mkdocs-material.fullname" . }}-entry
              configMap:
                name: {{ include "mkdocs-material.fullname" . }}-entry
                defaultMode: 0775
            {{- if .Values.storage.existing }}
            - name: {{ include "mkdocs-material.fullname" . }}-vol
              persistentVolumeClaim:
                claimName: {{ .Values.storage.existing }}
            {{- else }}
            - name: {{ include "mkdocs-material.fullname" . }}-vol
              persistentVolumeClaim:
                claimName: {{ include "mkdocs-material.fullname" . }}
            {{- end }}
            {{- if .Values.gitCredentialsSecret }}
            - name: {{ include "mkdocs-material.fullname" . }}-git-creds
              secret:
                secretName: {{ .Values.gitCredentialsSecret }}
                defaultMode: 0600
            {{- end }}
            {{- if .Values.certificateMap }}
            - name: certificates
              configMap:
                name: {{ .Values.certificateMap }}
            {{- end }}
            {{- if .Values.cacert }}
            - name: certificates
              configMap:
                name: {{ include "mkdocs-material.fullname" . }}-cacerts
            {{- end }}
            {{- if and .Values.macroPlugin.enabled .Values.macroPlugin.extraYamlConfig }}
            - name: {{ include "mkdocs-material.fullname" . }}-macro-vars
              configMap:
                name: {{ include "mkdocs-material.fullname" . }}-macro-vars
            {{- end }}

{{- end }}
