apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mkdocs-material.fullname" . }}
  labels:
    {{- include "mkdocs-material.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mkdocs-material.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mkdocs-material.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mkdocs-material.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "mkdocs-material.git-container" . | nindent 8 }}
        {{- include "mkdocs-material.mkdocs-container" . | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: {{ include "mkdocs-material.fullname" . }}
              subPath: nginx.conf
            - mountPath: /mkdocs
              name: {{ include "mkdocs-material.fullname" . }}-vol
              {{- if include "mkdocs-material.subpathPrefix" . }}
              subPath: {{ include "mkdocs-material.subpathPrefix" . | trimSuffix "/" }}
              {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- include "mkdocs-material.container-volumes" . | nindent 8 }}

