apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gameboard-api.fullname" . }}
  labels:
    {{- include "gameboard-api.labels" . | nindent 4 }}

data:
  appsettings.json: |
{{ .Values.settings | indent 4 }}
{{- if .Values.cacert }}
  ca-cert.crt: |
{{ .Values.cacert | indent 4 }}
  start.sh: |
    #!/bin/sh

    cp /start/ca-cert.crt /usr/local/share/ca-certificates
    update-ca-certificates
    cd /app
    dotnet Gameboard.Api.dll
{{- end }}
