apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "statesman-ui.fullname" . }}
  labels:
    {{- include "statesman-ui.labels" . | nindent 4 }}

data:
  settings.json: |-
{{ .Values.settings | indent 4 }}
