apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "staticweb.fullname" . }}
  labels:
    {{- include "staticweb.labels" . | nindent 4 }}

data:
  nginx.sh: |-
    #!/bin/sh
    sed -i "s,\},    text\/yaml yml yaml\;\n\}," /etc/nginx/mime.types
    sed -i "s,localhost;,localhost;\n    location ~ /\\\.git \{return 404;\}," /etc/nginx/conf.d/default.conf

  job.sh: |-
    #!/bin/sh

    giturl={{ .Values.giturl }}
    branch={{ .Values.gitbranch }}
    poll={{ .Values.pollInterval }}

    if [ -z "$giturl" ]; then
      echo no giturl provided.
      exit 1
    fi

    repo=$(echo $giturl | awk -F/ '{print $NF}' | sed  s,.git,,)

    ## get tools
    apk update && apk add git

    ## get source
    cd /html
    git clone $giturl .
    if [ -n "$branch" ]; then
      git checkout $branch
      git pull
    fi

    echo "*/$poll * * * * cd /html && git pull" >> /etc/crontabs/root

    crond -f -d8 > /proc/1/fd/1 2> /proc/1/fd/2
