apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity-ui.fullname" . }}
  labels:
    {{- include "identity-ui.labels" . | nindent 4 }}

data:
  settings.json: |
{{ .Values.settings | indent 4 }}

  setbase.sh: |
    #!/bin/sh
{{- if .Values.basehref }}
    basehref={{ .Values.basehref }}
    sed -i "s,base\ href=\"/\",base\ href=\"$basehref\"," /var/www/index.html
{{- end}}
